### ISSUE TITLE
Wrong documentation of BSMP command 0x0C

### ISSUE THREAD

**Issue by xresende** [lnls-sirius/libbsmp#1]
@pnallin , It is nice that this repo was uploaded to github. I updated links in the Sirius wiki to point to docs in this repo, instead of pointing to corresponding ones at our local git server.

I think there is a mistake in the english documentation of the BSMP command <code>0x0C</code>.  The _direction_ indicates from <code>Node</code> to <code>Master</code>. Should it not be <code>Master</code> to <code>Node</code> ? If this is indeed a mistake it is also in Revision 2.20. I did not check the portuguese version of the documentation.

**Comment by pnallin** [comment]
Indeed, I have just checked and there is a mistake! As you said, the direction should be Master -> Node (both in pt and en version).
I'll correct it soon. Thanks for pointing the issue.

**Comment by pnallin** [comment]
Done!
